name: compile tsc
run-name: ${{ github.actor }}'s ${{ github.event_name }} triggered compilation of TypeScript.
on:
  push:
    paths:
      - '**.ts'
jobs:
  compile-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '14'
      - name: Compiling TypeScript
      - run: |
          npm install -g typescript
          echo Directory pre-compilation
          tree
          tsc --project ts/tsconfig.json
          echo Directory post-compilation
          tree
      - name: Adding .js to repo
      - run: |
          git add
